services:
  - type: web
    name: swiss-recycling-assistant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dashboard.FINAL_DASHBOARD_BA_v2:server
    envVars:
      - key: OPENAI_API_KEY
        sync: false